"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import arg_services.mining.v1beta.entailment_pb2
import grpc

class EntailmentServiceStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    Entailments: grpc.UnaryUnaryMultiCallable[
        arg_services.mining.v1beta.entailment_pb2.EntailmentsRequest,
        arg_services.mining.v1beta.entailment_pb2.EntailmentsResponse,
    ]

class EntailmentServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Entailments(
        self,
        request: arg_services.mining.v1beta.entailment_pb2.EntailmentsRequest,
        context: grpc.ServicerContext,
    ) -> arg_services.mining.v1beta.entailment_pb2.EntailmentsResponse: ...

def add_EntailmentServiceServicer_to_server(servicer: EntailmentServiceServicer, server: grpc.Server) -> None: ...
