"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import arg_services.mining.v1beta.mining_pb2
import grpc

class MiningServiceStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    RunPipeline: grpc.UnaryUnaryMultiCallable[
        arg_services.mining.v1beta.mining_pb2.RunPipelineRequest,
        arg_services.mining.v1beta.mining_pb2.RunPipelineResponse,
    ]

class MiningServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def RunPipeline(
        self,
        request: arg_services.mining.v1beta.mining_pb2.RunPipelineRequest,
        context: grpc.ServicerContext,
    ) -> arg_services.mining.v1beta.mining_pb2.RunPipelineResponse: ...

def add_MiningServiceServicer_to_server(servicer: MiningServiceServicer, server: grpc.Server) -> None: ...
