# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ..core.datetime_utils import serialize_datetime


class DesignElementExport(pydantic.BaseModel):
    design_element_id: int
    design_element_created: str
    design_element_modified: str
    design_element_uid: str
    design_element_name: str
    design_element_description: str
    design_element_status: str
    design_element_category: str
    address: str
    network_operator_id: int
    network_operator: str
    element_work_template: str
    design_id: int
    design_element_region_id: int
    geometry_type: str
    longitude: float
    latitude: float
    measured_length: float
    custom_field_values: typing.Dict[str, typing.Any]
    extended_properties: typing.Dict[str, typing.Any]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        json_encoders = {dt.datetime: serialize_datetime}
