VERSION_YEAR = 2023
VERSION_MONTH = int('06')
VERSION_DAY = int('20')
VERSION_HOUR = int('13')
VERSION_MINUTE = int('43')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202306201343
version_date = '2023/06/20 13:43'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
