"""
    CCF-API

    This API provides programmatic access to data registered to the Human Reference Atlas (HRA). See the [HuBMAP HRA Portal](https://humanatlas.io/) for details.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ccf_openapi_client
from ccf_openapi_client.model.rgba import Rgba


class TestRgba(unittest.TestCase):
    """Rgba unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRgba(self):
        """Test Rgba"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Rgba()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
