
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-16T14:38:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "135d849660c7df74183379e7b2c1c99434095698",
 "version": "0.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
