# coding: utf-8

"""
    Kiln API Docs (dev)

    This API provides reporting staking data on various protocols as well as network wide data, staking transaction crafting features and so on. In order to use it, you should first get an API token from your Kiln dashboard (applications section). If you don't have access to our dashboard, please get in touch at hello@kiln.fi. Once you have your API token, you can set it as a bearer token in your request headers.  ### Backward Compatibility  This is an experimental specification used for development and testing, do not rely on what is here unless you know the implications.  The official Kiln API specification following backward compatible changes can be found [here](/).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@kiln.fi
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import kiln_connect.openapi_client
from kiln_connect.openapi_client.api.sol_api import SolApi  # noqa: E501
from kiln_connect.openapi_client.rest import ApiException


class TestSolApi(unittest.TestCase):
    """SolApi unit test stubs"""

    def setUp(self):
        self.api = kiln_connect.openapi_client.api.sol_api.SolApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_sol_network_stats(self):
        """Test case for get_sol_network_stats

        Network Stats  # noqa: E501
        """
        pass

    def test_get_sol_operations(self):
        """Test case for get_sol_operations

        Operations  # noqa: E501
        """
        pass

    def test_get_sol_reports(self):
        """Test case for get_sol_reports

        Reports  # noqa: E501
        """
        pass

    def test_get_sol_rewards(self):
        """Test case for get_sol_rewards

        Rewards  # noqa: E501
        """
        pass

    def test_get_sol_stakes(self):
        """Test case for get_sol_stakes

        Stakes  # noqa: E501
        """
        pass

    def test_get_sol_tx_status(self):
        """Test case for get_sol_tx_status

        Transaction Status  # noqa: E501
        """
        pass

    def test_post_sol_broadcast_tx(self):
        """Test case for post_sol_broadcast_tx

        Broadcast Transaction  # noqa: E501
        """
        pass

    def test_post_sol_deactivate_stake_tx(self):
        """Test case for post_sol_deactivate_stake_tx

        Deactivate Stake Transaction  # noqa: E501
        """
        pass

    def test_post_sol_merge_stakes_tx(self):
        """Test case for post_sol_merge_stakes_tx

        Merge Stakes Transaction  # noqa: E501
        """
        pass

    def test_post_sol_prepare_tx(self):
        """Test case for post_sol_prepare_tx

        Prepare Transaction  # noqa: E501
        """
        pass

    def test_post_sol_split_stake_tx(self):
        """Test case for post_sol_split_stake_tx

        Split Stake Transaction  # noqa: E501
        """
        pass

    def test_post_sol_stake_tx(self):
        """Test case for post_sol_stake_tx

        Stake Transaction  # noqa: E501
        """
        pass

    def test_post_sol_stakes(self):
        """Test case for post_sol_stakes

        Create stakes  # noqa: E501
        """
        pass

    def test_post_sol_withdraw_stake_tx(self):
        """Test case for post_sol_withdraw_stake_tx

        Withdraw Stake Transaction  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
