import abc
import builtins
import datetime
import enum
import typing

import jsii
import publication
import typing_extensions

from typeguard import check_type

import aws_cdk.alexa_ask._jsii
import aws_cdk.aws_accessanalyzer._jsii
import aws_cdk.aws_acmpca._jsii
import aws_cdk.aws_amazonmq._jsii
import aws_cdk.aws_amplify._jsii
import aws_cdk.aws_amplifyuibuilder._jsii
import aws_cdk.aws_apigateway._jsii
import aws_cdk.aws_apigatewayv2._jsii
import aws_cdk.aws_appconfig._jsii
import aws_cdk.aws_appflow._jsii
import aws_cdk.aws_appintegrations._jsii
import aws_cdk.aws_applicationautoscaling._jsii
import aws_cdk.aws_applicationinsights._jsii
import aws_cdk.aws_appmesh._jsii
import aws_cdk.aws_apprunner._jsii
import aws_cdk.aws_appstream._jsii
import aws_cdk.aws_appsync._jsii
import aws_cdk.aws_aps._jsii
import aws_cdk.aws_athena._jsii
import aws_cdk.aws_auditmanager._jsii
import aws_cdk.aws_autoscaling._jsii
import aws_cdk.aws_autoscalingplans._jsii
import aws_cdk.aws_backup._jsii
import aws_cdk.aws_backupgateway._jsii
import aws_cdk.aws_batch._jsii
import aws_cdk.aws_billingconductor._jsii
import aws_cdk.aws_budgets._jsii
import aws_cdk.aws_cassandra._jsii
import aws_cdk.aws_ce._jsii
import aws_cdk.aws_certificatemanager._jsii
import aws_cdk.aws_chatbot._jsii
import aws_cdk.aws_cloud9._jsii
import aws_cdk.aws_cloudfront._jsii
import aws_cdk.aws_cloudtrail._jsii
import aws_cdk.aws_cloudwatch._jsii
import aws_cdk.aws_codeartifact._jsii
import aws_cdk.aws_codebuild._jsii
import aws_cdk.aws_codecommit._jsii
import aws_cdk.aws_codedeploy._jsii
import aws_cdk.aws_codeguruprofiler._jsii
import aws_cdk.aws_codegurureviewer._jsii
import aws_cdk.aws_codepipeline._jsii
import aws_cdk.aws_codestar._jsii
import aws_cdk.aws_codestarconnections._jsii
import aws_cdk.aws_codestarnotifications._jsii
import aws_cdk.aws_cognito._jsii
import aws_cdk.aws_comprehend._jsii
import aws_cdk.aws_config._jsii
import aws_cdk.aws_connect._jsii
import aws_cdk.aws_connectcampaigns._jsii
import aws_cdk.aws_controltower._jsii
import aws_cdk.aws_cur._jsii
import aws_cdk.aws_customerprofiles._jsii
import aws_cdk.aws_databrew._jsii
import aws_cdk.aws_datapipeline._jsii
import aws_cdk.aws_datasync._jsii
import aws_cdk.aws_dax._jsii
import aws_cdk.aws_detective._jsii
import aws_cdk.aws_devopsguru._jsii
import aws_cdk.aws_directoryservice._jsii
import aws_cdk.aws_dlm._jsii
import aws_cdk.aws_dms._jsii
import aws_cdk.aws_docdb._jsii
import aws_cdk.aws_docdbelastic._jsii
import aws_cdk.aws_dynamodb._jsii
import aws_cdk.aws_ec2._jsii
import aws_cdk.aws_ecr._jsii
import aws_cdk.aws_ecs._jsii
import aws_cdk.aws_efs._jsii
import aws_cdk.aws_eks._jsii
import aws_cdk.aws_elasticache._jsii
import aws_cdk.aws_elasticbeanstalk._jsii
import aws_cdk.aws_elasticloadbalancing._jsii
import aws_cdk.aws_elasticloadbalancingv2._jsii
import aws_cdk.aws_elasticsearch._jsii
import aws_cdk.aws_emr._jsii
import aws_cdk.aws_emrcontainers._jsii
import aws_cdk.aws_emrserverless._jsii
import aws_cdk.aws_events._jsii
import aws_cdk.aws_eventschemas._jsii
import aws_cdk.aws_evidently._jsii
import aws_cdk.aws_finspace._jsii
import aws_cdk.aws_fis._jsii
import aws_cdk.aws_fms._jsii
import aws_cdk.aws_forecast._jsii
import aws_cdk.aws_frauddetector._jsii
import aws_cdk.aws_fsx._jsii
import aws_cdk.aws_gamelift._jsii
import aws_cdk.aws_globalaccelerator._jsii
import aws_cdk.aws_glue._jsii
import aws_cdk.aws_grafana._jsii
import aws_cdk.aws_greengrass._jsii
import aws_cdk.aws_greengrassv2._jsii
import aws_cdk.aws_groundstation._jsii
import aws_cdk.aws_guardduty._jsii
import aws_cdk.aws_healthlake._jsii
import aws_cdk.aws_iam._jsii
import aws_cdk.aws_identitystore._jsii
import aws_cdk.aws_imagebuilder._jsii
import aws_cdk.aws_inspector._jsii
import aws_cdk.aws_inspectorv2._jsii
import aws_cdk.aws_internetmonitor._jsii
import aws_cdk.aws_iot._jsii
import aws_cdk.aws_iot1click._jsii
import aws_cdk.aws_iotanalytics._jsii
import aws_cdk.aws_iotcoredeviceadvisor._jsii
import aws_cdk.aws_iotevents._jsii
import aws_cdk.aws_iotfleethub._jsii
import aws_cdk.aws_iotfleetwise._jsii
import aws_cdk.aws_iotsitewise._jsii
import aws_cdk.aws_iotthingsgraph._jsii
import aws_cdk.aws_iottwinmaker._jsii
import aws_cdk.aws_iotwireless._jsii
import aws_cdk.aws_ivs._jsii
import aws_cdk.aws_ivschat._jsii
import aws_cdk.aws_kafkaconnect._jsii
import aws_cdk.aws_kendra._jsii
import aws_cdk.aws_kendraranking._jsii
import aws_cdk.aws_kinesis._jsii
import aws_cdk.aws_kinesisanalytics._jsii
import aws_cdk.aws_kinesisanalyticsv2._jsii
import aws_cdk.aws_kinesisfirehose._jsii
import aws_cdk.aws_kinesisvideo._jsii
import aws_cdk.aws_kms._jsii
import aws_cdk.aws_lakeformation._jsii
import aws_cdk.aws_lambda._jsii
import aws_cdk.aws_lex._jsii
import aws_cdk.aws_licensemanager._jsii
import aws_cdk.aws_lightsail._jsii
import aws_cdk.aws_location._jsii
import aws_cdk.aws_logs._jsii
import aws_cdk.aws_lookoutequipment._jsii
import aws_cdk.aws_lookoutmetrics._jsii
import aws_cdk.aws_lookoutvision._jsii
import aws_cdk.aws_m2._jsii
import aws_cdk.aws_macie._jsii
import aws_cdk.aws_managedblockchain._jsii
import aws_cdk.aws_mediaconnect._jsii
import aws_cdk.aws_mediaconvert._jsii
import aws_cdk.aws_medialive._jsii
import aws_cdk.aws_mediapackage._jsii
import aws_cdk.aws_mediastore._jsii
import aws_cdk.aws_mediatailor._jsii
import aws_cdk.aws_memorydb._jsii
import aws_cdk.aws_msk._jsii
import aws_cdk.aws_mwaa._jsii
import aws_cdk.aws_neptune._jsii
import aws_cdk.aws_networkfirewall._jsii
import aws_cdk.aws_networkmanager._jsii
import aws_cdk.aws_nimblestudio._jsii
import aws_cdk.aws_oam._jsii
import aws_cdk.aws_omics._jsii
import aws_cdk.aws_opensearchserverless._jsii
import aws_cdk.aws_opensearchservice._jsii
import aws_cdk.aws_opsworks._jsii
import aws_cdk.aws_opsworkscm._jsii
import aws_cdk.aws_organizations._jsii
import aws_cdk.aws_osis._jsii
import aws_cdk.aws_panorama._jsii
import aws_cdk.aws_personalize._jsii
import aws_cdk.aws_pinpoint._jsii
import aws_cdk.aws_pinpointemail._jsii
import aws_cdk.aws_pipes._jsii
import aws_cdk.aws_proton._jsii
import aws_cdk.aws_qldb._jsii
import aws_cdk.aws_quicksight._jsii
import aws_cdk.aws_ram._jsii
import aws_cdk.aws_rds._jsii
import aws_cdk.aws_redshift._jsii
import aws_cdk.aws_redshiftserverless._jsii
import aws_cdk.aws_refactorspaces._jsii
import aws_cdk.aws_rekognition._jsii
import aws_cdk.aws_resiliencehub._jsii
import aws_cdk.aws_resourceexplorer2._jsii
import aws_cdk.aws_resourcegroups._jsii
import aws_cdk.aws_robomaker._jsii
import aws_cdk.aws_rolesanywhere._jsii
import aws_cdk.aws_route53._jsii
import aws_cdk.aws_route53recoverycontrol._jsii
import aws_cdk.aws_route53recoveryreadiness._jsii
import aws_cdk.aws_route53resolver._jsii
import aws_cdk.aws_rum._jsii
import aws_cdk.aws_s3._jsii
import aws_cdk.aws_s3objectlambda._jsii
import aws_cdk.aws_s3outposts._jsii
import aws_cdk.aws_sagemaker._jsii
import aws_cdk.aws_sam._jsii
import aws_cdk.aws_scheduler._jsii
import aws_cdk.aws_sdb._jsii
import aws_cdk.aws_secretsmanager._jsii
import aws_cdk.aws_securityhub._jsii
import aws_cdk.aws_servicecatalog._jsii
import aws_cdk.aws_servicecatalogappregistry._jsii
import aws_cdk.aws_servicediscovery._jsii
import aws_cdk.aws_ses._jsii
import aws_cdk.aws_shield._jsii
import aws_cdk.aws_signer._jsii
import aws_cdk.aws_simspaceweaver._jsii
import aws_cdk.aws_sns._jsii
import aws_cdk.aws_sqs._jsii
import aws_cdk.aws_ssm._jsii
import aws_cdk.aws_ssmcontacts._jsii
import aws_cdk.aws_ssmincidents._jsii
import aws_cdk.aws_sso._jsii
import aws_cdk.aws_stepfunctions._jsii
import aws_cdk.aws_supportapp._jsii
import aws_cdk.aws_synthetics._jsii
import aws_cdk.aws_systemsmanagersap._jsii
import aws_cdk.aws_timestream._jsii
import aws_cdk.aws_transfer._jsii
import aws_cdk.aws_voiceid._jsii
import aws_cdk.aws_vpclattice._jsii
import aws_cdk.aws_waf._jsii
import aws_cdk.aws_wafregional._jsii
import aws_cdk.aws_wafv2._jsii
import aws_cdk.aws_wisdom._jsii
import aws_cdk.aws_workspaces._jsii
import aws_cdk.aws_xray._jsii
import aws_cdk.core._jsii
import constructs._jsii

__jsii_assembly__ = jsii.JSIIAssembly.load(
    "@aws-cdk/cloudformation-include",
    "1.204.0",
    __name__[0:-6],
    "cloudformation-include@1.204.0.jsii.tgz",
)

__all__ = [
    "__jsii_assembly__",
]

publication.publish()
