# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/API.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobuf import A2L_pb2 as protobuf_dot_A2L__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protobuf/API.proto\x1a\x12protobuf/A2L.proto\"\x19\n\nA2LRequest\x12\x0b\n\x03\x61\x32l\x18\x01 \x01(\t\"8\n\x0b\x41\x32LResponse\x12\x0b\n\x03\x61\x32l\x18\x01 \x01(\t\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error\"e\n\x13JSONFromTreeRequest\x12\x1b\n\x04tree\x18\x01 \x01(\x0b\x32\r.RootNodeType\x12\x11\n\tsort_keys\x18\x02 \x01(\x08\x12\x13\n\x06indent\x18\x03 \x01(\rH\x00\x88\x01\x01\x42\t\n\x07_indent\"*\n\x0bTreeRequest\x12\x1b\n\x04tree\x18\x01 \x01(\x0b\x32\r.RootNodeType\"I\n\x0cTreeResponse\x12\x1b\n\x04tree\x18\x01 \x01(\x0b\x32\r.RootNodeType\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error\"\x1b\n\x0bJSONRequest\x12\x0c\n\x04json\x18\x01 \x01(\t\":\n\x0cJSONResponse\x12\x0c\n\x04json\x18\x01 \x01(\t\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error2\xd1\x01\n\x03\x41\x32L\x12.\n\x0eGetTreeFromA2L\x12\x0b.A2LRequest\x1a\r.TreeResponse\"\x00\x12\x38\n\x0fGetJSONFromTree\x12\x14.JSONFromTreeRequest\x1a\r.JSONResponse\"\x00\x12\x30\n\x0fGetTreeFromJSON\x12\x0c.JSONRequest\x1a\r.TreeResponse\"\x00\x12.\n\x0eGetA2LFromTree\x12\x0c.TreeRequest\x1a\x0c.A2LResponse\"\x00\x42\x0eZ\x0c./../pkg/a2lb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.API_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\014./../pkg/a2l'
  _A2LREQUEST._serialized_start=42
  _A2LREQUEST._serialized_end=67
  _A2LRESPONSE._serialized_start=69
  _A2LRESPONSE._serialized_end=125
  _JSONFROMTREEREQUEST._serialized_start=127
  _JSONFROMTREEREQUEST._serialized_end=228
  _TREEREQUEST._serialized_start=230
  _TREEREQUEST._serialized_end=272
  _TREERESPONSE._serialized_start=274
  _TREERESPONSE._serialized_end=347
  _JSONREQUEST._serialized_start=349
  _JSONREQUEST._serialized_end=376
  _JSONRESPONSE._serialized_start=378
  _JSONRESPONSE._serialized_end=436
  _A2L._serialized_start=439
  _A2L._serialized_end=648
# @@protoc_insertion_point(module_scope)
