# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.0rc1.dev10+g8f253a3.d20230614'
__version_tuple__ = version_tuple = (1, 0, 'dev10', 'g8f253a3.d20230614')
