# -*- coding: utf-8 -*-

"""
    mundiapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import mundiapi.models.card_11

class TokensRequest(object):

    """Implementation of the 'Tokens Request' model.

    TODO: type model description here.

    Attributes:
        mtype (string): Token type
        card (Card11): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype":'type',
        "card":'card'
    }

    def __init__(self,
                 mtype=None,
                 card=None):
        """Constructor for the TokensRequest class"""

        # Initialize members of the class
        self.mtype = mtype
        self.card = card


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype = dictionary.get('type')
        card = mundiapi.models.card_11.Card11.from_dictionary(dictionary.get('card')) if dictionary.get('card') else None

        # Return an object of this model
        return cls(mtype,
                   card)


