# coding: utf-8

"""
    Kiln API Docs (dev)

    This API provides reporting staking data on various protocols as well as network wide data, staking transaction crafting features and so on. In order to use it, you should first get an API token from your Kiln dashboard (applications section). If you don't have access to our dashboard, please get in touch at hello@kiln.fi. Once you have your API token, you can set it as a bearer token in your request headers.  ### Backward Compatibility  This is an experimental specification used for development and testing, do not rely on what is here unless you know the implications.  The official Kiln API specification following backward compatible changes can be found [here](/).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@kiln.fi
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kiln_connect.openapi_client
from kiln_connect.openapi_client.models.portfolio import Portfolio  # noqa: E501
from kiln_connect.openapi_client.rest import ApiException

class TestPortfolio(unittest.TestCase):
    """Portfolio unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Portfolio
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Portfolio`
        """
        model = kiln_connect.openapi_client.models.portfolio.Portfolio()  # noqa: E501
        if include_optional :
            return Portfolio(
                total_balance_usd = 182981229.16751668, 
                total_rewards_usd = 4526.16751668, 
                total_stakes = 56, 
                total_active_stakes = 52, 
                protocols = [
                    kiln_connect.openapi_client.models.portfolio_protocols_inner.Portfolio_protocols_inner(
                        token = 'eth', 
                        name = 'Ethereum', 
                        total_stakes = 12, 
                        total_active_stakes = 10, 
                        total_balance = kiln_connect.openapi_client.models.portfolio_protocols_inner_total_balance.Portfolio_protocols_inner_total_balance(
                            amount_usd = 10896.4568, 
                            amount = 1896.4563, ), 
                        total_rewards = kiln_connect.openapi_client.models.portfolio_protocols_inner_total_rewards.Portfolio_protocols_inner_total_rewards(
                            amount_usd = 10896.4568, 
                            amount = 1896.4568, ), 
                        balance_share_percent = 42.59, 
                        rewards_share_percent = 42.59, )
                    ]
            )
        else :
            return Portfolio(
        )
        """

    def testPortfolio(self):
        """Test Portfolio"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
