# coding: utf-8

"""
    Kiln API Docs (dev)

    This API provides reporting staking data on various protocols as well as network wide data, staking transaction crafting features and so on. In order to use it, you should first get an API token from your Kiln dashboard (applications section). If you don't have access to our dashboard, please get in touch at hello@kiln.fi. Once you have your API token, you can set it as a bearer token in your request headers.  ### Backward Compatibility  This is an experimental specification used for development and testing, do not rely on what is here unless you know the implications.  The official Kiln API specification following backward compatible changes can be found [here](/).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@kiln.fi
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kiln_connect.openapi_client
from kiln_connect.openapi_client.models.post_xtz_stake_tx201_response import PostXtzStakeTx201Response  # noqa: E501
from kiln_connect.openapi_client.rest import ApiException

class TestPostXtzStakeTx201Response(unittest.TestCase):
    """PostXtzStakeTx201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PostXtzStakeTx201Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostXtzStakeTx201Response`
        """
        model = kiln_connect.openapi_client.models.post_xtz_stake_tx201_response.PostXtzStakeTx201Response()  # noqa: E501
        if include_optional :
            return PostXtzStakeTx201Response(
                data = kiln_connect.openapi_client.models.xtz_unsigned_tx.XTZUnsignedTx(
                    unsigned_tx_hash = '7383fbcd64c1d95c92b5ebee44a569f15e557a773b6d733ab7bb4e3ce98de812', 
                    unsigned_tx_serialized = 'aef6da4e377364f07c2aa460d7148a8971dab767417b541fa473b2d8e038974f6e00566eaa0198f3df9230489abd1a64f5ef9b98b270940ac4cb9807f44e00ff00344c5e59a1de5370e1cee5d2fcf706a649bba15b', 
                    unsigned_tx = {"branch":"BM3LZcG2SNz2DCWVGAAvT3gd8Vc17dS649CG6o9PhwJjmpUTptA","contents":[{"kind":"delegation","source":"tz1TX3Nh6h6js1VxXCuQ7rAF7LoGpd81FSw3","fee":"1300","counter":"15082948","gas_limit":"10100","storage_limit":"0","delegate":"tz1QQZKGt3ouyd7x8JUDwcvRyxzsmD7CFbMd"}]}, )
            )
        else :
            return PostXtzStakeTx201Response(
        )
        """

    def testPostXtzStakeTx201Response(self):
        """Test PostXtzStakeTx201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
