# coding: utf-8

"""
    Kiln API Docs (dev)

    This API provides reporting staking data on various protocols as well as network wide data, staking transaction crafting features and so on. In order to use it, you should first get an API token from your Kiln dashboard (applications section). If you don't have access to our dashboard, please get in touch at hello@kiln.fi. Once you have your API token, you can set it as a bearer token in your request headers.  ### Backward Compatibility  This is an experimental specification used for development and testing, do not rely on what is here unless you know the implications.  The official Kiln API specification following backward compatible changes can be found [here](/).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@kiln.fi
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field

class ETHNetworkStats(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    network_gross_apy: Optional[float] = Field(None, description="Gross annual percentage yield")
    supply_staked_percent: Optional[float] = Field(None, description="Supply of Ethereum currently staked")
    eth_price_usd: Optional[float] = Field(None, description="Price of Ethereum in USD")
    estimated_entry_time_seconds: Optional[float] = Field(None, description="Estimated queue entry time in seconds from a deposit to an active stake")
    estimated_exit_time_seconds: Optional[float] = Field(None, description="Estimated queue exit time in seconds from an exit request to an exited stake")
    estimated_withdrawal_time_seconds: Optional[float] = Field(None, description="Estimated time for a stake to receive Consensus rewards on the execution layer")
    __properties = ["network_gross_apy", "supply_staked_percent", "eth_price_usd", "estimated_entry_time_seconds", "estimated_exit_time_seconds", "estimated_withdrawal_time_seconds"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ETHNetworkStats:
        """Create an instance of ETHNetworkStats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ETHNetworkStats:
        """Create an instance of ETHNetworkStats from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return ETHNetworkStats.parse_obj(obj)

        _obj = ETHNetworkStats.parse_obj({
            "network_gross_apy": obj.get("network_gross_apy"),
            "supply_staked_percent": obj.get("supply_staked_percent"),
            "eth_price_usd": obj.get("eth_price_usd"),
            "estimated_entry_time_seconds": obj.get("estimated_entry_time_seconds"),
            "estimated_exit_time_seconds": obj.get("estimated_exit_time_seconds"),
            "estimated_withdrawal_time_seconds": obj.get("estimated_withdrawal_time_seconds")
        })
        return _obj

