VERSION_YEAR = 2023
VERSION_MONTH = int('06')
VERSION_DAY = int('16')
VERSION_HOUR = int('03')
VERSION_MINUTE = int('14')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202306160314
version_date = '2023/06/16 03:14'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
