MAIN_KEY = "main:app"
EMPTY_STRING = ""

STATUS_CODE_KEY = "status_code"
DETAIL_MESSAGE_KEY = "detail_message"
ERROR_RESPONSE_DETAIL_KEY = "detail"
AUTHORIZATION_KEY = "Authorization"


HTTP_200_OK = 200
HTTP_201_CREATED = 201
HTTP_401_UNAUTHORIZED = 401
HTTP_403_FORBIDDEN = 403
HTTP_404_NOT_FOUND = 404
HTTP_409_CONFLICT = 409

IMAGE_BASE_FOLDER = "images"

READ_BINARY_MODE = "rb"
WRITE_BINARY_MODE = "wb"

IMAGE_PNG_CONTENT_TYPE = "image/png"

HOST_ENV_VARIABLE_KEY = "HOST"
HOST_DEFAULT = "localhost"

PORT_ENV_VARIABLE_KEY = "PORT"
PORT_DEFAULT = 8000

WELCOM_MESSAGE_ENV_VARIABLE_KEY = "WELCOME_MESSAGE"

DATABASE_URI_ENV_VARIABLE_KEY = "DATABASE_URI"
DATABASE_URI_DEFAULT = "sqlite:///sqlite.db"

TEST_DATABASE_URI_ENV_VARIABLE_KEY = "TEST_DATABASE_URI"
TEST_DATABASE_URI_DEFAULT = "sqlite:///test.db"

ROOT_ROUTE = '/'