# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frequenz/api/dispatch/fcr/prequalification.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0frequenz/api/dispatch/fcr/prequalification.proto\x12*frequenz.api.dispatch.fcr.prequalification\"\x81\x02\n\x1b\x46\x63rPrequalificationSettings\x12$\n\x17power_limit_preparation\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\"\n\x15power_limit_operation\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x1c\n\x0fsoc_bound_upper\x18\x03 \x01(\rH\x02\x88\x01\x01\x12\x1c\n\x0fsoc_bound_lower\x18\x04 \x01(\rH\x03\x88\x01\x01\x42\x1a\n\x18_power_limit_preparationB\x18\n\x16_power_limit_operationB\x12\n\x10_soc_bound_upperB\x12\n\x10_soc_bound_lowerb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frequenz.api.dispatch.fcr.prequalification_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FCRPREQUALIFICATIONSETTINGS._serialized_start=97
  _FCRPREQUALIFICATIONSETTINGS._serialized_end=354
# @@protoc_insertion_point(module_scope)
