VERSION_YEAR = 2023
VERSION_MONTH = int('06')
VERSION_DAY = int('14')
VERSION_HOUR = int('18')
VERSION_MINUTE = int('07')
MAJOR_VERSION = 1
MINOR_VERSION = 14
PATCH_VERSION = 202306141807
version_date = '2023/06/14 18:07'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
