VERSION_YEAR = 2023
VERSION_MONTH = int('06')
VERSION_DAY = int('20')
VERSION_HOUR = int('14')
VERSION_MINUTE = int('19')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202306201419
version_date = '2023/06/20 14:19'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
