VERSION_YEAR = 2023
VERSION_MONTH = int('06')
VERSION_DAY = int('16')
VERSION_HOUR = int('05')
VERSION_MINUTE = int('52')
MAJOR_VERSION = 0
MINOR_VERSION = 31
PATCH_VERSION = 202306160552
version_date = '2023/06/16 05:52'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
