"""
OstatsLib Configuration module
"""

# Diagnostics tests
FULL_PENALIZED_PVALUE = 0.01
PARTIAL_PENALIZED_PVALUE = 0.05

# Environment
MAX_STEPS = 10

# Rewards limits
REWARD_RANGE = (-1, 1)
MIN_REWARD = REWARD_RANGE[0]
MAX_REWARD = REWARD_RANGE[1]
EXPLORATORY_REWARD_FRACTION = 0.5
MAX_EXPLORATORY_REWARD = MAX_REWARD * EXPLORATORY_REWARD_FRACTION

# Scores
MIN_ACCEPTED_SCORE = 0.6
