VERSION_YEAR = 2023
VERSION_MONTH = int('06')
VERSION_DAY = int('18')
VERSION_HOUR = int('22')
VERSION_MINUTE = int('21')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202306182221
version_date = '2023/06/18 22:21'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
