# Generated by Django 4.2.2 on 2023-06-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_productimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rootcategory",
            options={
                "verbose_name": "RootCategory",
                "verbose_name_plural": "Root Categories",
            },
        ),
        migrations.CreateModel(
            name="GroupedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True, verbose_name="status")),
                (
                    "url_key",
                    models.CharField(
                        help_text="Enter the url key of the search engine",
                        max_length=250,
                        verbose_name="url_key",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        help_text="Enter the meta title of the search engine",
                        max_length=250,
                        verbose_name="meta_title",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        help_text="Enter the meta description of the search engine",
                        max_length=250,
                        verbose_name="meta_description",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        help_text="Enter the meta keywords of the search engine",
                        max_length=250,
                        verbose_name="meta_keywords",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the grouped product",
                        max_length=250,
                        verbose_name="name",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Enter the sku of the grouped product",
                        max_length=250,
                        verbose_name="sku",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Enter the description of the grouped product",
                        verbose_name="description",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="Enter the short description of the grouped product",
                        verbose_name="short_description",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        help_text="Select the product",
                        to="product.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grouped Product",
                "verbose_name_plural": "Grouped Products",
            },
        ),
    ]
